[package]
name = "cpio-deku"
version = "0.1.0"
edition = "2021"

[features]
default = ["std"]
std = ["deku/std", "alloc"]
alloc = ["deku/alloc"]

[dependencies]
clap = { version = "4.4.12", features = ["derive"] }
deku = { git = "https://github.com/sharksforarms/deku", branch = "impl-reader-seek" }

[dev-dependencies]
tempfile = "3.9.0"
test-assets = { git  = "https://github.com/wcampbell0x2a/test-assets", branch = "replace-curl-ureq" }
